export const chartLineOptions = {
  backgroundColor: 'transparent',
  borderColor: '#E3FFA8',
  borderWidth: 1,
  pointBorderColor: '#0F0F0F',
  pointBackgroundColor: '#E3FFA8',
  pointBorderWidth: 1,
  pointHoverRadius: 8,
  pointHoverBackgroundColor: '#E3FFA8',
  pointHoverBorderColor: '#0F0F0F',
  pointHoverBorderWidth: 1,
  pointRadius: 2,
  pointHitRadius: 20,
  fill: true,
  tension: 0.5,
};